create table Products (
	id INT,
	product_name VARCHAR(50),
	account_id VARCHAR(100)
);
insert into Products (id, product_name, account_id) values (1, 'Sriracha Chili Sauce', '81,29');
insert into Products (id, product_name, account_id) values (2, 'Sculpting Kit', '81,80');
insert into Products (id, product_name, account_id) values (3, 'Electric Food Steamer', '90,12');
insert into Products (id, product_name, account_id) values (4, 'Carrot Ginger Soup', '28,23');
insert into Products (id, product_name, account_id) values (5, 'Portable Pet Pooper Scooper', '61,18');
insert into Products (id, product_name, account_id) values (6, 'Adjustable Laptop Stand', '93,83');
insert into Products (id, product_name, account_id) values (7, 'Gluten-Free Pancake Mix', '70,62');
insert into Products (id, product_name, account_id) values (8, 'Noise-Canceling Earbuds', '75,84');
insert into Products (id, product_name, account_id) values (9, 'Oven-Baked Potato Chips', '85,22');
insert into Products (id, product_name, account_id) values (10, 'Organic Tomato Ketchup', '60,96');
insert into Products (id, product_name, account_id) values (11, 'Mushrooms', '58,38');
insert into Products (id, product_name, account_id) values (12, 'Garlic Herb Cream Cheese', '35,87');
insert into Products (id, product_name, account_id) values (13, 'Instant Read Meat Thermometer', '74,64');
insert into Products (id, product_name, account_id) values (14, 'Luxury Memory Foam Mattress Topper', '62,96');
insert into Products (id, product_name, account_id) values (15, 'Himalayan Pink Salt', '48,31');
insert into Products (id, product_name, account_id) values (16, 'Warm Wool Sweater', '11,84');
insert into Products (id, product_name, account_id) values (17, 'High-Top Leather Boots', '27,8');
insert into Products (id, product_name, account_id) values (18, 'Wire Shelving Unit', '32,33');
insert into Products (id, product_name, account_id) values (19, 'Cauliflower Gnocchi', '29,93');
insert into Products (id, product_name, account_id) values (20, 'Chocolate Chip Muffins', '20,42');
insert into Products (id, product_name, account_id) values (21, 'Flavored Rice Cakes', '23,36');
insert into Products (id, product_name, account_id) values (22, 'Portable Grill Cover', '62,27');
insert into Products (id, product_name, account_id) values (23, 'Beard Grooming Kit', '2,43');
insert into Products (id, product_name, account_id) values (24, 'Wooden Toy Train Set', '62,93');
insert into Products (id, product_name, account_id) values (25, 'Wireless Mouse', '37,81');
insert into Products (id, product_name, account_id) values (26, 'Luxury Bathrobe', '77,43');
insert into Products (id, product_name, account_id) values (27, 'Lentil Pasta', '35,50');
insert into Products (id, product_name, account_id) values (28, 'Compact Umbrella', '56,2');
insert into Products (id, product_name, account_id) values (29, 'Wireless Charger', '80,14');
insert into Products (id, product_name, account_id) values (30, 'Bamboo Toothbrush Holder', '24,94');
insert into Products (id, product_name, account_id) values (31, 'Pet Travel Bowl', '8,51');
insert into Products (id, product_name, account_id) values (32, 'Spicy Snack Mix', '17,51');
insert into Products (id, product_name, account_id) values (33, 'Mediterranean Couscous Salad', '55,98');
insert into Products (id, product_name, account_id) values (34, 'Maple Bacon Potato Chips', '60,23');
insert into Products (id, product_name, account_id) values (35, 'Smartphone Hand Grip', '5,79');
insert into Products (id, product_name, account_id) values (36, 'Juice Extractor', '7,85');
insert into Products (id, product_name, account_id) values (37, 'Smart LED Desk Lamp', '74,83');
insert into Products (id, product_name, account_id) values (38, 'Classic Slim Fit Shirt', '29,46');
insert into Products (id, product_name, account_id) values (39, 'Stylish Combat Boots', '44,16');
insert into Products (id, product_name, account_id) values (40, 'Jennifer''s Amazing Lip Balm Kit', '92,42');
insert into Products (id, product_name, account_id) values (41, 'Buffalo Cauliflower Bites', '6,30');
insert into Products (id, product_name, account_id) values (42, 'Coconut Cashew Yogurt', '52,81');
insert into Products (id, product_name, account_id) values (43, 'Roasted Chickpeas', '10,77');
insert into Products (id, product_name, account_id) values (44, 'Garlic Herb Seasoning', '51,74');
insert into Products (id, product_name, account_id) values (45, 'Lemon Lime Sparkling Water', '99,55');
insert into Products (id, product_name, account_id) values (46, 'Wire Shelving Unit', '52,90');
insert into Products (id, product_name, account_id) values (47, 'Cinnamon Roll Protein Bar', '53,54');
insert into Products (id, product_name, account_id) values (48, 'Green Smoothie Mix', '82,51');
insert into Products (id, product_name, account_id) values (49, 'Compressed Towel Tablets', '9,38');
insert into Products (id, product_name, account_id) values (50, 'Green Smoothie Mix', '61,50');
insert into Products (id, product_name, account_id) values (51, 'Sports Windbreaker', '76,29');
insert into Products (id, product_name, account_id) values (52, 'Spicy Thai Chili Sauce', '11,78');
insert into Products (id, product_name, account_id) values (53, 'Sesame Oil', '97,73');
insert into Products (id, product_name, account_id) values (54, 'Ripped Boyfriend Jeans', '3,62');
insert into Products (id, product_name, account_id) values (55, 'Insulated Lunch Bag', '73,91');
insert into Products (id, product_name, account_id) values (56, 'Chipotle Sauce', '85,74');
insert into Products (id, product_name, account_id) values (57, 'Herbal Tea Sampler Box', '81,69');
insert into Products (id, product_name, account_id) values (58, 'Frozen Broccoli', '84,55');
insert into Products (id, product_name, account_id) values (59, 'Pocket Blanket', '56,49');
insert into Products (id, product_name, account_id) values (60, 'Compact Shoe Rack', '64,71');
insert into Products (id, product_name, account_id) values (61, 'Safety First Aid Kit', '42,6');
insert into Products (id, product_name, account_id) values (62, 'Smart Plug', '17,87');
insert into Products (id, product_name, account_id) values (63, 'Pasta (Fusilli)', '71,16');
insert into Products (id, product_name, account_id) values (64, 'Wall Decals for Kids', '17,91');
insert into Products (id, product_name, account_id) values (65, 'Cotton Basic Tank', '38,86');
insert into Products (id, product_name, account_id) values (66, 'Puffer Winter Coat', '80,49');
insert into Products (id, product_name, account_id) values (67, 'Honey BBQ Riblets', '57,13');
insert into Products (id, product_name, account_id) values (68, 'Organic Quinoa Salad', '73,2');
insert into Products (id, product_name, account_id) values (69, 'Chicken Sausage', '90,49');
insert into Products (id, product_name, account_id) values (70, 'Dark Chocolate Covered Raisins', '86,54');
insert into Products (id, product_name, account_id) values (71, 'Motion Sensor Light', '76,57');
insert into Products (id, product_name, account_id) values (72, 'Outdoor Fire Pit', '15,29');
insert into Products (id, product_name, account_id) values (73, 'Kids'' Gardening Kit', '73,74');
insert into Products (id, product_name, account_id) values (74, 'Tennis Racket', '99,76');
insert into Products (id, product_name, account_id) values (75, 'Vegetable Curry', '60,66');
insert into Products (id, product_name, account_id) values (76, 'Beef Taco Skillet', '73,71');
insert into Products (id, product_name, account_id) values (77, 'Noise-Canceling Headphones', '58,48');
insert into Products (id, product_name, account_id) values (78, 'Fire Roasted Salsa', '65,2');
insert into Products (id, product_name, account_id) values (79, 'Smart Plug', '52,2');
insert into Products (id, product_name, account_id) values (80, 'Electric Rice Cooker with Steamer', '16,85');
insert into Products (id, product_name, account_id) values (81, 'Pasta (Linguine)', '16,34');
insert into Products (id, product_name, account_id) values (82, 'Whole Grain Cereal', '69,62');
insert into Products (id, product_name, account_id) values (83, 'Sesame Seeds', '86,94');
insert into Products (id, product_name, account_id) values (84, 'Pineapple Salsa', '88,58');
insert into Products (id, product_name, account_id) values (85, 'Backpacking Tent', '30,85');
insert into Products (id, product_name, account_id) values (86, 'Asian Stir-Fry Kit', '30,40');
insert into Products (id, product_name, account_id) values (87, 'Aged White Cheddar Popcorn', '21,67');
insert into Products (id, product_name, account_id) values (88, 'DIY Candle Making Kit', '43,11');
insert into Products (id, product_name, account_id) values (89, 'Fitness Jump Rope with LCD Counter', '23,75');
insert into Products (id, product_name, account_id) values (90, 'Eco-Friendly Yoga Blocks', '57,76');
insert into Products (id, product_name, account_id) values (91, 'Stuffed Grape Leaves', '19,20');
insert into Products (id, product_name, account_id) values (92, 'Fitness Activity Journal', '79,34');
insert into Products (id, product_name, account_id) values (93, 'Stuffed Grape Leaves', '37,81');
insert into Products (id, product_name, account_id) values (94, 'Herb Garden Planter Box', '95,31');
insert into Products (id, product_name, account_id) values (95, 'Honey Almond Granola Bars', '54,99');
insert into Products (id, product_name, account_id) values (96, 'Frozen Spinach', '7,75');
insert into Products (id, product_name, account_id) values (97, 'Smart LED Light Strip', '38,57');
insert into Products (id, product_name, account_id) values (98, 'Chunky Knit Sweater', '49,93');
insert into Products (id, product_name, account_id) values (99, 'Durable Hiking Boots', '17,37');
insert into Products (id, product_name, account_id) values (100, 'Almond Milk', '37,20');
insert into Products (id, product_name, account_id) values (101, 'Dog Training Whistle', '17,9');
insert into Products (id, product_name, account_id) values (102, 'Sunglasses', '8,67');
insert into Products (id, product_name, account_id) values (103, 'Smartphone Photography Tripod', '71,36');
insert into Products (id, product_name, account_id) values (104, 'Fitness Jump Rope', '20,66');
insert into Products (id, product_name, account_id) values (105, 'Shoe Organizer', '27,87');
insert into Products (id, product_name, account_id) values (106, 'Sweet and Sour Sauce', '55,82');
insert into Products (id, product_name, account_id) values (107, 'Fitness Resistance Bands', '72,12');
insert into Products (id, product_name, account_id) values (108, 'Cabbage Slaw Mix', '97,97');
insert into Products (id, product_name, account_id) values (109, 'Grapes (red)', '92,67');
insert into Products (id, product_name, account_id) values (110, 'Video Camera', '30,95');
insert into Products (id, product_name, account_id) values (111, 'Couscous Mix', '76,9');
insert into Products (id, product_name, account_id) values (112, 'Halloween Decoration Set', '20,46');
insert into Products (id, product_name, account_id) values (113, 'Microfiber Cleaning Cloth Set', '100,87');
insert into Products (id, product_name, account_id) values (114, 'Multi-Function Meat Tenderizer', '15,87');
insert into Products (id, product_name, account_id) values (115, 'Organic Honeycrisp Apples', '64,78');
insert into Products (id, product_name, account_id) values (116, 'Sliced Cucumbers', '58,13');
insert into Products (id, product_name, account_id) values (117, 'Oven-Baked Cheese Crisps', '19,20');
insert into Products (id, product_name, account_id) values (118, 'Beef Stroganoff Meal Kit', '66,65');
insert into Products (id, product_name, account_id) values (119, 'Canvas High-Top Sneakers', '69,24');
insert into Products (id, product_name, account_id) values (120, 'Cable Knit Beanie', '83,81');
insert into Products (id, product_name, account_id) values (121, 'Wall-Mounted Spice Rack', '3,32');
insert into Products (id, product_name, account_id) values (122, 'Electric Stool Heater', '41,26');
insert into Products (id, product_name, account_id) values (123, 'Savory Quinoa Pudding', '65,32');
insert into Products (id, product_name, account_id) values (124, 'Hummus', '9,52');
insert into Products (id, product_name, account_id) values (125, 'Quinoa and Kale Salad Kit', '36,82');
insert into Products (id, product_name, account_id) values (126, 'Chocolate Chip Cliff Bars', '88,79');
insert into Products (id, product_name, account_id) values (127, 'Electric Bike', '71,49');
insert into Products (id, product_name, account_id) values (128, 'Creamy Tomato Basil Soup', '95,10');
insert into Products (id, product_name, account_id) values (129, 'Sesame Garlic Noodles', '21,76');
insert into Products (id, product_name, account_id) values (130, 'Outdoor Camping Hammock', '29,100');
insert into Products (id, product_name, account_id) values (131, 'Spinach Pizza Rolls', '86,3');
insert into Products (id, product_name, account_id) values (132, 'Beard Grooming Kit', '20,44');
insert into Products (id, product_name, account_id) values (133, 'Travel Mug', '48,90');
insert into Products (id, product_name, account_id) values (134, 'Organic Coconut Water', '51,85');
insert into Products (id, product_name, account_id) values (135, 'Mango Chutney', '30,91');
insert into Products (id, product_name, account_id) values (136, 'Sweet Corn Fritters', '49,54');
insert into Products (id, product_name, account_id) values (137, 'Portable Phone Charger', '75,72');
insert into Products (id, product_name, account_id) values (138, 'Chili Beans (canned)', '49,11');
insert into Products (id, product_name, account_id) values (139, 'Frozen Berry Blend', '37,72');
insert into Products (id, product_name, account_id) values (140, 'Artisan Pickles', '48,21');
insert into Products (id, product_name, account_id) values (141, 'Portable Solar Charger', '86,78');
insert into Products (id, product_name, account_id) values (142, 'Cordless Electric Screwdriver', '5,87');
insert into Products (id, product_name, account_id) values (143, 'Collapsible Pet Dog Bowl', '49,16');
insert into Products (id, product_name, account_id) values (144, 'Herb Garlic Butter', '32,59');
insert into Products (id, product_name, account_id) values (145, 'Honey Almond Granola Bars', '93,40');
insert into Products (id, product_name, account_id) values (146, 'Lemon Herb Grilled Chicken', '22,86');
insert into Products (id, product_name, account_id) values (147, 'Chickpea Pasta', '14,40');
insert into Products (id, product_name, account_id) values (148, 'Chocolate Coconut Granola', '29,92');
insert into Products (id, product_name, account_id) values (149, 'Inflatable Pool Float', '5,8');
insert into Products (id, product_name, account_id) values (150, 'Electric Heat Press Machine', '5,60');
insert into Products (id, product_name, account_id) values (151, 'Artisan Pickles', '3,18');
insert into Products (id, product_name, account_id) values (152, 'Bike Helmet', '81,85');
insert into Products (id, product_name, account_id) values (153, 'Warm Knit Beanie', '23,43');
insert into Products (id, product_name, account_id) values (154, 'Ground Cinnamon', '9,5');
insert into Products (id, product_name, account_id) values (155, 'Fruit Medley Juice', '35,100');
insert into Products (id, product_name, account_id) values (156, 'Herb Garden Planter Box', '97,19');
insert into Products (id, product_name, account_id) values (157, 'Portable Bluetooth Keyboard', '9,3');
insert into Products (id, product_name, account_id) values (158, 'Eco-Friendly Cleaning Cloths', '84,51');
insert into Products (id, product_name, account_id) values (159, 'Bicycle Repair Kit', '58,3');
insert into Products (id, product_name, account_id) values (160, 'Organic Almonds', '2,99');
insert into Products (id, product_name, account_id) values (161, 'Weighted Blanket for Adults', '51,78');
insert into Products (id, product_name, account_id) values (162, 'Athletic Sports Bra', '66,40');
insert into Products (id, product_name, account_id) values (163, 'Smartphone Projector Kit', '81,25');
insert into Products (id, product_name, account_id) values (164, 'Garden Tool Belt', '100,29');
insert into Products (id, product_name, account_id) values (165, 'Warm Wool Sweater', '41,8');
insert into Products (id, product_name, account_id) values (166, 'Kettle Chip Variety Pack', '29,64');
insert into Products (id, product_name, account_id) values (167, 'Smart Light Bulbs', '7,48');
insert into Products (id, product_name, account_id) values (168, 'Smartphone Car Mount with Wireless Charging', '97,79');
insert into Products (id, product_name, account_id) values (169, 'Crispy Tofu Bites', '66,10');
insert into Products (id, product_name, account_id) values (170, 'Plant Watering Spikes', '6,0');
insert into Products (id, product_name, account_id) values (171, 'Relaxed Fit Henley Shirt', '56,48');
insert into Products (id, product_name, account_id) values (172, 'Frozen Vegetarian Pizza', '17,24');
insert into Products (id, product_name, account_id) values (173, 'Sliced Ham', '77,84');
insert into Products (id, product_name, account_id) values (174, 'Caraway Rye Bread', '95,64');
insert into Products (id, product_name, account_id) values (175, 'Grapes (red)', '23,74');
insert into Products (id, product_name, account_id) values (176, 'Waffle Maker', '48,31');
insert into Products (id, product_name, account_id) values (177, 'Sour Cream', '95,15');
insert into Products (id, product_name, account_id) values (178, 'Running Shorts', '7,32');
insert into Products (id, product_name, account_id) values (179, 'Stainless Steel Water Pitcher', '62,90');
insert into Products (id, product_name, account_id) values (180, 'Pepper Jack Cheese Slices', '87,89');
insert into Products (id, product_name, account_id) values (181, 'Pizza Stone', '68,81');
insert into Products (id, product_name, account_id) values (182, 'Ice Cream Scoop', '54,39');
insert into Products (id, product_name, account_id) values (183, 'Animal Paw Print Soap Dispenser', '94,34');
insert into Products (id, product_name, account_id) values (184, 'Savory Quinoa Pudding', '37,65');
insert into Products (id, product_name, account_id) values (185, 'Wireless Keyboard and Mouse Combo', '87,76');
insert into Products (id, product_name, account_id) values (186, 'Ice Cream Scoop', '20,3');
insert into Products (id, product_name, account_id) values (187, 'Microwave Popcorn Maker', '51,28');
insert into Products (id, product_name, account_id) values (188, 'Camera Tripod', '75,6');
insert into Products (id, product_name, account_id) values (189, 'Garlic & Herb Goat Cheese', '37,31');
insert into Products (id, product_name, account_id) values (190, 'Greek Feta Cheese', '70,82');
insert into Products (id, product_name, account_id) values (191, 'Beef Sirloin Steak', '93,31');
insert into Products (id, product_name, account_id) values (192, 'Freestanding Wine Rack', '55,63');
insert into Products (id, product_name, account_id) values (193, 'Wireless Earbuds', '21,48');
insert into Products (id, product_name, account_id) values (194, 'LED Under Cabinet Lighting', '72,37');
insert into Products (id, product_name, account_id) values (195, 'Couscous', '10,26');
insert into Products (id, product_name, account_id) values (196, 'Sliced Avocado', '3,81');
insert into Products (id, product_name, account_id) values (197, 'Wireless Keyboard and Mouse Combo', '57,54');
insert into Products (id, product_name, account_id) values (198, 'LED Desk Lamp with USB Charging', '17,59');
insert into Products (id, product_name, account_id) values (199, 'Chocolate Peanut Butter Cups', '5,59');
insert into Products (id, product_name, account_id) values (200, 'Dual Function Electric Skillet', '70,59');
insert into Products (id, product_name, account_id) values (201, 'Thai Green Curry Paste', '43,28');
insert into Products (id, product_name, account_id) values (202, 'Creamy Ranch Dressing', '20,38');
insert into Products (id, product_name, account_id) values (203, 'Reflective Safety Vest', '89,42');
insert into Products (id, product_name, account_id) values (204, 'Oven Mitts', '37,21');
insert into Products (id, product_name, account_id) values (205, 'Cat Scratching Post with Toys', '60,70');
insert into Products (id, product_name, account_id) values (206, 'Roasted Garlic Mashed Potatoes', '14,53');
insert into Products (id, product_name, account_id) values (207, 'Nut Butter Cups', '15,21');
insert into Products (id, product_name, account_id) values (208, 'Homestyle Beef Stew', '7,49');
insert into Products (id, product_name, account_id) values (209, 'Over-the-Door Hooks', '76,9');
insert into Products (id, product_name, account_id) values (210, 'Pet Water Bottle', '25,66');
insert into Products (id, product_name, account_id) values (211, 'Luxury Bathrobe', '44,14');
insert into Products (id, product_name, account_id) values (212, 'Black Bean Spaghetti', '4,100');
insert into Products (id, product_name, account_id) values (213, 'Bluetooth Shower Speaker', '98,60');
insert into Products (id, product_name, account_id) values (214, 'Samsung Galaxy Smartwatch', '18,49');
insert into Products (id, product_name, account_id) values (215, 'Beach Cover-Up', '36,96');
insert into Products (id, product_name, account_id) values (216, 'Spicy Beef Taco Mix', '66,67');
insert into Products (id, product_name, account_id) values (217, 'LED Canopy Lights', '49,59');
insert into Products (id, product_name, account_id) values (218, 'Collapsible Storage Crates', '74,93');
insert into Products (id, product_name, account_id) values (219, 'Soft Plush Throw Blanket', '11,51');
insert into Products (id, product_name, account_id) values (220, 'Cauliflower Gnocchi', '17,68');
insert into Products (id, product_name, account_id) values (221, 'Pet Grooming Scissors', '94,88');
insert into Products (id, product_name, account_id) values (222, 'Organic Ramen Noodles', '24,50');
insert into Products (id, product_name, account_id) values (223, 'Potato Wedge Seasoning', '91,65');
insert into Products (id, product_name, account_id) values (224, 'Almond Butter Cups', '62,45');
insert into Products (id, product_name, account_id) values (225, 'Inspirational Wall Art', '31,9');
insert into Products (id, product_name, account_id) values (226, 'Wireless Induction Charger', '3,6');
insert into Products (id, product_name, account_id) values (227, 'Sesame Oil', '72,34');
insert into Products (id, product_name, account_id) values (228, 'Vacuum Sealer Machine', '30,99');
insert into Products (id, product_name, account_id) values (229, 'Caraway Rye Bread', '37,35');
insert into Products (id, product_name, account_id) values (230, 'Stainless Steel Mixing Bowls', '81,81');
insert into Products (id, product_name, account_id) values (231, 'Vegetable Stir-Fry Sauce', '14,76');
insert into Products (id, product_name, account_id) values (232, 'Dark Chocolate Covered Raisins', '74,8');
insert into Products (id, product_name, account_id) values (233, 'Pecan Pie Filling', '20,9');
insert into Products (id, product_name, account_id) values (234, 'Pet Travel Bed', '11,31');
insert into Products (id, product_name, account_id) values (235, 'Juice Extractor', '81,18');
insert into Products (id, product_name, account_id) values (236, 'Animal Paw Print Soap Dispenser', '58,20');
insert into Products (id, product_name, account_id) values (237, 'Puzzle Mat', '88,24');
insert into Products (id, product_name, account_id) values (238, 'Mediterranean Chickpea Bowl', '75,27');
insert into Products (id, product_name, account_id) values (239, 'Lemon Garlic Marinade', '9,100');
insert into Products (id, product_name, account_id) values (240, 'Puff Pastry', '95,43');
insert into Products (id, product_name, account_id) values (241, 'Artisan Cornbread Mix', '21,84');
insert into Products (id, product_name, account_id) values (242, 'Sooji (Semolina)', '86,52');
insert into Products (id, product_name, account_id) values (243, 'Coconut Rice', '90,71');
insert into Products (id, product_name, account_id) values (244, 'Fruit and Nut Bars', '90,81');
insert into Products (id, product_name, account_id) values (245, 'Reversible Swimming Pool Lounger', '91,69');
insert into Products (id, product_name, account_id) values (246, 'Rechargeable Electric Screwdriver', '65,14');
insert into Products (id, product_name, account_id) values (247, 'Slim Fit Chinos', '47,69');
insert into Products (id, product_name, account_id) values (248, 'Sliced Cheese', '57,83');
insert into Products (id, product_name, account_id) values (249, 'Graphic Hoodie', '34,20');
insert into Products (id, product_name, account_id) values (250, 'Salsa', '57,41');
insert into Products (id, product_name, account_id) values (251, 'Wireless Keyboard and Mouse Combo', '89,77');
insert into Products (id, product_name, account_id) values (252, 'Matcha Green Tea Powder', '21,28');
insert into Products (id, product_name, account_id) values (253, 'Induction Cooktop', '6,48');
insert into Products (id, product_name, account_id) values (254, 'Pet Travel Carrier', '20,22');
insert into Products (id, product_name, account_id) values (255, 'Fashionable Scarves Set', '68,59');
insert into Products (id, product_name, account_id) values (256, 'Caramelized Onion Dip Mix', '49,19');
insert into Products (id, product_name, account_id) values (257, 'Vegan Chickpea Salad', '44,0');
insert into Products (id, product_name, account_id) values (258, 'Fitness Jump Rope with LCD Counter', '85,71');
insert into Products (id, product_name, account_id) values (259, 'Greek Yogurt Parfait', '52,95');
insert into Products (id, product_name, account_id) values (260, 'Plant-Based Meal Prep Containers', '7,3');
insert into Products (id, product_name, account_id) values (261, 'Mashed Sweet Potatoes', '91,5');
insert into Products (id, product_name, account_id) values (262, 'Travel Yoga Mat', '46,59');
insert into Products (id, product_name, account_id) values (263, 'Salsa Verde', '19,93');
insert into Products (id, product_name, account_id) values (264, 'Pumpkin Spice Cookies', '15,67');
insert into Products (id, product_name, account_id) values (265, 'Electric Pressure Cooker', '53,10');
insert into Products (id, product_name, account_id) values (266, 'Indian Curry Sauce', '66,88');
insert into Products (id, product_name, account_id) values (267, 'Self-Watering Planters', '8,85');
insert into Products (id, product_name, account_id) values (268, 'Balsamic Fig Dressing', '15,100');
insert into Products (id, product_name, account_id) values (269, 'Silicone Stretch Lids', '49,47');
insert into Products (id, product_name, account_id) values (270, 'Dark Chocolate Raisins', '100,16');
insert into Products (id, product_name, account_id) values (271, 'Flavored Rice Cakes', '6,31');
insert into Products (id, product_name, account_id) values (272, 'Chickpea Flour', '92,67');
insert into Products (id, product_name, account_id) values (273, 'Peanut Butter Banana Smoothie', '91,25');
insert into Products (id, product_name, account_id) values (274, 'Professional Chef Knife', '24,3');
insert into Products (id, product_name, account_id) values (275, 'Balsamic Salad Dressing', '82,78');
insert into Products (id, product_name, account_id) values (276, 'Sea Salt Caramel Brownie', '27,35');
insert into Products (id, product_name, account_id) values (277, 'Reversible Swimming Pool Lounger', '42,55');
insert into Products (id, product_name, account_id) values (278, 'Honey Sesame Cashews', '66,19');
insert into Products (id, product_name, account_id) values (279, 'Quinoa & Black Bean Salad', '35,23');
insert into Products (id, product_name, account_id) values (280, 'Coconut Chia Seed Pudding', '84,18');
insert into Products (id, product_name, account_id) values (281, 'Organic Spinach', '7,100');
insert into Products (id, product_name, account_id) values (282, 'Honey Mustard Pretzel Bites', '76,84');
insert into Products (id, product_name, account_id) values (283, 'Outdoor Camping Hammock', '35,33');
insert into Products (id, product_name, account_id) values (284, 'Maxi Wrap Dress', '94,17');
insert into Products (id, product_name, account_id) values (285, 'Brown Sugar', '30,13');
insert into Products (id, product_name, account_id) values (286, 'Multi-Functional Rice Cooker', '40,58');
insert into Products (id, product_name, account_id) values (287, 'Sports Windbreaker', '47,96');
insert into Products (id, product_name, account_id) values (288, 'Wireless Induction Charger', '83,93');
insert into Products (id, product_name, account_id) values (289, 'Beef Taco Skillet', '24,93');
insert into Products (id, product_name, account_id) values (290, 'Crispy Tofu Bites', '36,77');
insert into Products (id, product_name, account_id) values (291, 'Coconut Cream Pie Mix', '94,15');
insert into Products (id, product_name, account_id) values (292, 'Safety Goggles', '47,24');
insert into Products (id, product_name, account_id) values (293, 'Classic Slim Fit Shirt', '99,22');
insert into Products (id, product_name, account_id) values (294, 'Organic Almonds', '52,10');
insert into Products (id, product_name, account_id) values (295, 'Wooden Puzzle Game', '71,7');
insert into Products (id, product_name, account_id) values (296, 'Wireless Earbuds', '78,30');
insert into Products (id, product_name, account_id) values (297, 'Brussels Sprouts', '27,95');
insert into Products (id, product_name, account_id) values (298, 'Strawberry Banana Smoothie Pack', '31,61');
insert into Products (id, product_name, account_id) values (299, 'Sweet Potato and Chickpea Bowl', '33,10');
insert into Products (id, product_name, account_id) values (300, 'Honey Ginger Tea', '28,44');
insert into Products (id, product_name, account_id) values (301, 'Beef Stew Meat', '6,39');
insert into Products (id, product_name, account_id) values (302, 'Peanut Butter Pretzel Nuggets', '62,19');
insert into Products (id, product_name, account_id) values (303, 'Chili Lime Seasoning', '64,49');
insert into Products (id, product_name, account_id) values (304, 'Backpack', '81,11');
insert into Products (id, product_name, account_id) values (305, 'Teriyaki Sauce', '65,22');
insert into Products (id, product_name, account_id) values (306, 'Insulated Cooler', '50,72');
insert into Products (id, product_name, account_id) values (307, 'Smartphone Tripod', '66,13');
insert into Products (id, product_name, account_id) values (308, 'Dark Chocolate Covered Raisins', '69,28');
insert into Products (id, product_name, account_id) values (309, 'Cauliflower Crust Pizza', '71,61');
insert into Products (id, product_name, account_id) values (310, 'Fitness Tracker Watch', '81,96');
insert into Products (id, product_name, account_id) values (311, 'Chocolate Hazelnut Granola', '43,15');
insert into Products (id, product_name, account_id) values (312, 'Pet Water Bottle', '2,66');
insert into Products (id, product_name, account_id) values (313, 'Hiking Boots', '10,93');
insert into Products (id, product_name, account_id) values (314, 'Honey Glazed Carrots', '12,31');
insert into Products (id, product_name, account_id) values (315, 'Mini Waffle Maker', '88,53');
insert into Products (id, product_name, account_id) values (316, 'Electric Stir Fry Pan', '44,61');
insert into Products (id, product_name, account_id) values (317, 'Collapsible Folding Chair', '7,85');
insert into Products (id, product_name, account_id) values (318, 'Savory Breakfast Sausage', '41,86');
insert into Products (id, product_name, account_id) values (319, 'Elegant Lace Dress', '5,56');
insert into Products (id, product_name, account_id) values (320, 'Vintage Graphic Tee', '83,24');
insert into Products (id, product_name, account_id) values (321, 'Set of Measuring Spoons', '87,16');
insert into Products (id, product_name, account_id) values (322, 'Ultra-Thin Laptop Sleeve', '46,10');
insert into Products (id, product_name, account_id) values (323, 'Chocolate Coconut Protein Balls', '66,6');
insert into Products (id, product_name, account_id) values (324, 'Bamboo Bathtub Caddy', '14,6');
insert into Products (id, product_name, account_id) values (325, 'Chocolate Hazelnut Spread', '28,25');
insert into Products (id, product_name, account_id) values (326, 'Classic Minestrone Soup', '43,78');
insert into Products (id, product_name, account_id) values (327, 'Window Bird Feeder', '71,17');
insert into Products (id, product_name, account_id) values (328, 'Honey Wheat Pretzels', '39,68');
insert into Products (id, product_name, account_id) values (329, 'Asian Salad Mix', '3,93');
insert into Products (id, product_name, account_id) values (330, 'Cauliflower Pizza Crust', '87,70');
insert into Products (id, product_name, account_id) values (331, 'Honey Butter Popcorn', '68,63');
insert into Products (id, product_name, account_id) values (332, 'Buffalo Cauliflower Bites', '11,18');
insert into Products (id, product_name, account_id) values (333, 'Carrot and Celery Sticks', '70,62');
insert into Products (id, product_name, account_id) values (334, 'Balsamic Glazed Brussels Sprouts', '14,1');
insert into Products (id, product_name, account_id) values (335, 'Lemon Dill Salmon', '52,26');
insert into Products (id, product_name, account_id) values (336, 'Thermostatic Shower Valve Kit', '96,65');
insert into Products (id, product_name, account_id) values (337, 'Spinach and Cheese Stuffed Shells', '90,69');
insert into Products (id, product_name, account_id) values (338, 'Reusable Produce Bags Set', '57,43');
insert into Products (id, product_name, account_id) values (339, 'LED Desk Lamp with USB Charging', '32,20');
insert into Products (id, product_name, account_id) values (340, 'Herb Drying Rack', '82,18');
insert into Products (id, product_name, account_id) values (341, 'Fruit and Nut Bars', '14,85');
insert into Products (id, product_name, account_id) values (342, 'Low-Fat Yogurt', '81,31');
insert into Products (id, product_name, account_id) values (343, 'Organic Quinoa Salad', '27,61');
insert into Products (id, product_name, account_id) values (344, 'Decorative Throw Blanket', '41,15');
insert into Products (id, product_name, account_id) values (345, 'Pet Leash', '17,28');
insert into Products (id, product_name, account_id) values (346, 'Cable Knit Cardigan', '84,53');
insert into Products (id, product_name, account_id) values (347, 'Collapsible Storage Crates', '68,71');
insert into Products (id, product_name, account_id) values (348, 'Classic Caesar Dressing', '61,47');
insert into Products (id, product_name, account_id) values (349, 'Trail Mix (Deluxe)', '87,16');
insert into Products (id, product_name, account_id) values (350, 'Luminous Night Light', '19,18');
insert into Products (id, product_name, account_id) values (351, 'Ceramic Non-Stick Frying Pan', '68,67');
insert into Products (id, product_name, account_id) values (352, 'High-Waisted Skirt', '59,29');
insert into Products (id, product_name, account_id) values (353, 'Frozen Cauliflower Rice', '14,65');
insert into Products (id, product_name, account_id) values (354, 'Caramel Apple Chips', '46,45');
insert into Products (id, product_name, account_id) values (355, 'Peach Slices in Syrup', '26,77');
insert into Products (id, product_name, account_id) values (356, 'Smart Water Bottle with Hydration Reminder', '91,83');
insert into Products (id, product_name, account_id) values (357, 'Vintage Button-Down Shirt', '66,22');
insert into Products (id, product_name, account_id) values (358, 'Portable Phone Mug Holder', '0,44');
insert into Products (id, product_name, account_id) values (359, 'Digital Camera', '70,97');
insert into Products (id, product_name, account_id) values (360, 'Infrared Thermometer', '92,0');
insert into Products (id, product_name, account_id) values (361, 'Chipotle Sauce', '85,17');
insert into Products (id, product_name, account_id) values (362, 'Vegetable Spiralizer', '46,43');
insert into Products (id, product_name, account_id) values (363, 'Lemon Pepper Seasoning', '47,43');
insert into Products (id, product_name, account_id) values (364, 'Foldable Picnic Table', '94,85');
insert into Products (id, product_name, account_id) values (365, 'LED Makeup Mirror', '55,29');
insert into Products (id, product_name, account_id) values (366, 'Wall-Mounted Organizer', '84,20');
insert into Products (id, product_name, account_id) values (367, 'Pasta (Fusilli)', '94,90');
insert into Products (id, product_name, account_id) values (368, 'Fitness Tracker', '2,99');
insert into Products (id, product_name, account_id) values (369, 'Vegan Mayonnaise', '64,45');
insert into Products (id, product_name, account_id) values (370, 'Laptop Sleeve', '1,70');
insert into Products (id, product_name, account_id) values (371, 'Coconut Chips', '17,95');
insert into Products (id, product_name, account_id) values (372, 'Kids'' Crafting Station', '92,9');
insert into Products (id, product_name, account_id) values (373, 'Poppy Seed Dressing', '65,21');
insert into Products (id, product_name, account_id) values (374, 'Spicy Snack Mix', '42,96');
insert into Products (id, product_name, account_id) values (375, 'Mixed Berry Smoothie Pack', '12,92');
insert into Products (id, product_name, account_id) values (376, 'Eco-Friendly Cleaning Cloths', '20,35');
insert into Products (id, product_name, account_id) values (377, 'Folding Exercise Bike', '84,21');
insert into Products (id, product_name, account_id) values (378, 'Stylish Combat Boots', '29,92');
insert into Products (id, product_name, account_id) values (379, 'Savory Breakfast Sausage', '28,78');
insert into Products (id, product_name, account_id) values (380, 'Gluten-Free Pancake Mix', '19,85');
insert into Products (id, product_name, account_id) values (381, 'Portable Hammock', '1,24');
insert into Products (id, product_name, account_id) values (382, 'Multi-Functional Rice Cooker', '46,38');
insert into Products (id, product_name, account_id) values (383, 'Vegetable Chips', '97,19');
insert into Products (id, product_name, account_id) values (384, 'Personal Blender with Travel Lid', '26,74');
insert into Products (id, product_name, account_id) values (385, 'Dried Mango Slices', '51,92');
insert into Products (id, product_name, account_id) values (386, 'Non-Toxic Concrete Sealer', '17,91');
insert into Products (id, product_name, account_id) values (387, 'Balsamic Glazed Brussels Sprouts', '18,48');
insert into Products (id, product_name, account_id) values (388, 'Silicone Ice Cube Tray', '30,78');
insert into Products (id, product_name, account_id) values (389, 'Car Seat Organizer', '37,84');
insert into Products (id, product_name, account_id) values (390, 'Green Tea Matcha Powder', '41,34');
insert into Products (id, product_name, account_id) values (391, 'Rainbow Veggie Chips', '33,89');
insert into Products (id, product_name, account_id) values (392, 'Portable Charcoal Grill', '8,89');
insert into Products (id, product_name, account_id) values (393, 'Electric Heat Press Machine', '51,4');
insert into Products (id, product_name, account_id) values (394, 'Wireless Charging Station', '47,8');
insert into Products (id, product_name, account_id) values (395, 'Magnetic Screen Door', '100,9');
insert into Products (id, product_name, account_id) values (396, 'Oven-Baked Cheese Crisps', '47,56');
insert into Products (id, product_name, account_id) values (397, 'Non-Stick Baking Sheets', '50,73');
insert into Products (id, product_name, account_id) values (398, 'Yoga Mat', '62,55');
insert into Products (id, product_name, account_id) values (399, 'Thai Coconut Curry Sauce', '4,86');
insert into Products (id, product_name, account_id) values (400, 'Smartphone Stand', '89,47');
insert into Products (id, product_name, account_id) values (401, 'Chocolate Chip Cliff Bars', '52,78');
insert into Products (id, product_name, account_id) values (402, 'Almond Butter Granola Bars', '76,12');
insert into Products (id, product_name, account_id) values (403, 'Elderberry Syrup', '65,83');
insert into Products (id, product_name, account_id) values (404, 'Camera Tripod', '59,30');
insert into Products (id, product_name, account_id) values (405, 'Thai Red Curry Paste', '6,42');
insert into Products (id, product_name, account_id) values (406, 'Veggie Chips Variety Pack', '74,98');
insert into Products (id, product_name, account_id) values (407, 'Instant Read Meat Thermometer', '2,40');
insert into Products (id, product_name, account_id) values (408, 'Smart Air Purifier', '6,70');
insert into Products (id, product_name, account_id) values (409, 'Frozen Chicken Nuggets', '10,21');
insert into Products (id, product_name, account_id) values (410, 'Pasta (Linguine)', '2,92');
insert into Products (id, product_name, account_id) values (411, 'Radish Chips', '52,12');
insert into Products (id, product_name, account_id) values (412, 'Electric Knife', '27,41');
insert into Products (id, product_name, account_id) values (413, 'Elderberry Syrup Kit', '0,67');
insert into Products (id, product_name, account_id) values (414, 'Cinnamon Roll Kit', '72,70');
insert into Products (id, product_name, account_id) values (415, 'Chocolate Peanut Butter Cups', '84,29');
insert into Products (id, product_name, account_id) values (416, 'Ripped Boyfriend Jeans', '2,99');
insert into Products (id, product_name, account_id) values (417, 'Puzzle Game Set', '65,56');
insert into Products (id, product_name, account_id) values (418, 'Potting Soil', '26,64');
insert into Products (id, product_name, account_id) values (419, 'Indoor Grill', '65,52');
insert into Products (id, product_name, account_id) values (420, 'Kids'' Crafting Station', '2,68');
insert into Products (id, product_name, account_id) values (421, 'Set of Silicone Baking Molds', '14,34');
insert into Products (id, product_name, account_id) values (422, 'Sturdy Bookends', '28,3');
insert into Products (id, product_name, account_id) values (423, 'Decorative Throw Pillows', '48,13');
insert into Products (id, product_name, account_id) values (424, 'Vegan Chocolate Cake Mix', '39,83');
insert into Products (id, product_name, account_id) values (425, 'Sweet Chili Thai Sauce', '89,88');
insert into Products (id, product_name, account_id) values (426, 'Cinnamon Sugar Popcorn', '47,19');
insert into Products (id, product_name, account_id) values (427, 'Multi-Layer Food Steamer', '51,32');
insert into Products (id, product_name, account_id) values (428, 'Artisan Pickles', '11,32');
insert into Products (id, product_name, account_id) values (429, 'Grapes (red)', '45,78');
insert into Products (id, product_name, account_id) values (430, 'LED Disco Ball Light', '84,16');
insert into Products (id, product_name, account_id) values (431, 'Tomato Sauce', '32,61');
insert into Products (id, product_name, account_id) values (432, 'Garden Hose', '3,29');
insert into Products (id, product_name, account_id) values (433, 'Italian Herb Balsamic Marinade', '45,79');
insert into Products (id, product_name, account_id) values (434, 'Paint By Numbers Kit', '2,36');
insert into Products (id, product_name, account_id) values (435, 'Peach Mango Smoothie', '49,23');
insert into Products (id, product_name, account_id) values (436, 'Stuffed Bell Peppers', '23,72');
insert into Products (id, product_name, account_id) values (437, 'Maple Breakfast Sausage', '30,13');
insert into Products (id, product_name, account_id) values (438, 'Automatic Pet Feeder', '82,38');
insert into Products (id, product_name, account_id) values (439, 'Electric Wax Warmer', '52,8');
insert into Products (id, product_name, account_id) values (440, 'Insulated Sport Tumbler', '22,53');
insert into Products (id, product_name, account_id) values (441, 'Heavy-Duty Utility Tote', '62,85');
insert into Products (id, product_name, account_id) values (442, 'Tandoori Chicken Skewers', '25,98');
insert into Products (id, product_name, account_id) values (443, 'Kids'' Art Supplies Kit', '44,15');
insert into Products (id, product_name, account_id) values (444, 'Asian Salad Mix', '63,45');
insert into Products (id, product_name, account_id) values (445, 'Roasted Sweet Corn', '74,37');
insert into Products (id, product_name, account_id) values (446, 'Sesame Noodles', '27,36');
insert into Products (id, product_name, account_id) values (447, 'Savory Pumpkin Soup', '43,26');
insert into Products (id, product_name, account_id) values (448, 'Black Bean Soup', '99,79');
insert into Products (id, product_name, account_id) values (449, 'Foot Massager', '63,46');
insert into Products (id, product_name, account_id) values (450, 'Dried Mango Slices', '8,40');
insert into Products (id, product_name, account_id) values (451, 'Almond Flour Tortillas', '65,62');
insert into Products (id, product_name, account_id) values (452, 'Athletic Sports Bra', '99,70');
insert into Products (id, product_name, account_id) values (453, 'Spicy Roasted Nuts', '42,67');
insert into Products (id, product_name, account_id) values (454, 'Quality Chef Apron', '44,10');
insert into Products (id, product_name, account_id) values (455, 'Self-Massaging Pillow', '75,50');
insert into Products (id, product_name, account_id) values (456, 'Apple Cinnamon Oatmeal', '79,46');
insert into Products (id, product_name, account_id) values (457, 'Cinnamon Sugar Popcorn', '4,6');
insert into Products (id, product_name, account_id) values (458, 'Essential Oil Diffuser', '58,56');
insert into Products (id, product_name, account_id) values (459, 'Buffalo Wing Sauce', '45,12');
insert into Products (id, product_name, account_id) values (460, 'Miso Dressing', '78,79');
insert into Products (id, product_name, account_id) values (461, 'Sweet Potato Fries', '14,99');
insert into Products (id, product_name, account_id) values (462, 'Baked Potato Chips', '57,55');
insert into Products (id, product_name, account_id) values (463, 'Roasted Red Pepper Dip', '9,40');
insert into Products (id, product_name, account_id) values (464, 'Underwater Camera', '78,70');
insert into Products (id, product_name, account_id) values (465, 'Skincare Fridge', '80,85');
insert into Products (id, product_name, account_id) values (466, 'Pet Travel Bed', '47,18');
insert into Products (id, product_name, account_id) values (467, 'Caramelized Onion Dip Mix', '42,79');
insert into Products (id, product_name, account_id) values (468, 'Sports Water Bottle with Infuser', '15,83');
insert into Products (id, product_name, account_id) values (469, 'Hibiscus Tea Bags', '9,9');
insert into Products (id, product_name, account_id) values (470, 'Cranberry Citrus Sauce', '26,89');
insert into Products (id, product_name, account_id) values (471, 'Electric Knife', '78,2');
insert into Products (id, product_name, account_id) values (472, 'Pet First Aid Kit', '99,80');
insert into Products (id, product_name, account_id) values (473, 'Whole Wheat Bread', '23,42');
insert into Products (id, product_name, account_id) values (474, 'Spinach Pizza Rolls', '18,89');
insert into Products (id, product_name, account_id) values (475, 'Cranberry Pecan Granola', '88,63');
insert into Products (id, product_name, account_id) values (476, 'Chocolate Mint Protein Shake', '95,60');
insert into Products (id, product_name, account_id) values (477, 'Pressure Cooker', '47,69');
insert into Products (id, product_name, account_id) values (478, 'Pineapple Teriyaki Chicken Mix', '95,40');
insert into Products (id, product_name, account_id) values (479, 'Jennifer''s Amazing Lip Balm Kit', '13,37');
insert into Products (id, product_name, account_id) values (480, 'Portable UV Sterilizer', '43,96');
insert into Products (id, product_name, account_id) values (481, 'Gardening Fairy Figurines', '98,73');
insert into Products (id, product_name, account_id) values (482, 'Wall Art Stickers', '82,96');
insert into Products (id, product_name, account_id) values (483, 'Multi-Port USB Hub', '45,13');
insert into Products (id, product_name, account_id) values (484, 'Vegetable Stir-Fry Kit', '70,88');
insert into Products (id, product_name, account_id) values (485, 'Portable Hand Warmer', '36,68');
insert into Products (id, product_name, account_id) values (486, 'Herbed Couscous', '62,37');
insert into Products (id, product_name, account_id) values (487, 'Maple Chipotle Glaze', '90,99');
insert into Products (id, product_name, account_id) values (488, 'Reversible Comforter Set', '80,98');
insert into Products (id, product_name, account_id) values (489, 'Overnight Hiking Backpack', '51,29');
insert into Products (id, product_name, account_id) values (490, 'Kids'' Gardening Tools Set', '54,78');
insert into Products (id, product_name, account_id) values (491, 'Pet Caress Brush', '36,13');
insert into Products (id, product_name, account_id) values (492, 'Athletic Sports Bra', '36,65');
insert into Products (id, product_name, account_id) values (493, 'Dark Chocolate Covered Almonds', '1,27');
insert into Products (id, product_name, account_id) values (494, 'Faux Fur Coat', '42,7');
insert into Products (id, product_name, account_id) values (495, 'Electric Air Pump', '3,29');
insert into Products (id, product_name, account_id) values (496, 'Sweet Potato and Chickpea Bowl', '29,17');
insert into Products (id, product_name, account_id) values (497, 'Desk Lamp with USB Port', '100,13');
insert into Products (id, product_name, account_id) values (498, 'Classic Vanilla Fudge', '67,44');
insert into Products (id, product_name, account_id) values (499, 'LED Strip Lights', '81,64');
insert into Products (id, product_name, account_id) values (500, 'Bluetooth Headphones', '71,8');
insert into Products (id, product_name, account_id) values (501, 'Fishing Tackle Box', '48,15');
insert into Products (id, product_name, account_id) values (502, 'LED Desk Light', '11,0');
insert into Products (id, product_name, account_id) values (503, 'Sustainable Wooden Toys', '40,73');
insert into Products (id, product_name, account_id) values (504, 'Wine Decanter', '56,98');
insert into Products (id, product_name, account_id) values (505, 'Spaghetti Sauce', '69,17');
insert into Products (id, product_name, account_id) values (506, 'Bluetooth Car Adapter', '98,63');
insert into Products (id, product_name, account_id) values (507, 'Cherry Almond Protein Bar', '59,76');
insert into Products (id, product_name, account_id) values (508, 'Kettle Chip Variety Pack', '62,7');
insert into Products (id, product_name, account_id) values (509, 'Heart-Shaped Baking Molds', '93,0');
insert into Products (id, product_name, account_id) values (510, 'Screen Cleaning Kit', '12,73');
insert into Products (id, product_name, account_id) values (511, 'Granola', '20,28');
insert into Products (id, product_name, account_id) values (512, 'Whole Chicken', '68,70');
insert into Products (id, product_name, account_id) values (513, 'Ribbed Knit Dress', '58,69');
insert into Products (id, product_name, account_id) values (514, 'Self-Inflating Camping Mattress', '50,66');
insert into Products (id, product_name, account_id) values (515, 'Smart Thermostat', '8,9');
insert into Products (id, product_name, account_id) values (516, 'Cocktail Shaker and Mixing Glass Set', '89,10');
insert into Products (id, product_name, account_id) values (517, 'Oven Thermometer', '74,90');
insert into Products (id, product_name, account_id) values (518, 'Frozen Spinach', '77,7');
insert into Products (id, product_name, account_id) values (519, 'Avocado Lime Dressing', '75,25');
insert into Products (id, product_name, account_id) values (520, 'Buttermilk Pancakes', '6,82');
insert into Products (id, product_name, account_id) values (521, 'Home Karaoke System', '16,19');
insert into Products (id, product_name, account_id) values (522, 'Beach Cover-Up', '45,38');
insert into Products (id, product_name, account_id) values (523, 'Outdoor Picnic Blanket', '62,90');
insert into Products (id, product_name, account_id) values (524, 'Smartphone Gimbal', '17,15');
insert into Products (id, product_name, account_id) values (525, 'Fitness Jump Rope', '36,57');
insert into Products (id, product_name, account_id) values (526, 'Garden Vegetable Chips', '50,31');
insert into Products (id, product_name, account_id) values (527, 'Sweet Potato Tots', '12,51');
insert into Products (id, product_name, account_id) values (528, 'Desk Organizer Set', '63,66');
insert into Products (id, product_name, account_id) values (529, 'Collapsible Camping Cup', '33,59');
insert into Products (id, product_name, account_id) values (530, 'Marinara Sauce', '2,18');
insert into Products (id, product_name, account_id) values (531, 'Electronic Drum Kit', '79,10');
insert into Products (id, product_name, account_id) values (532, 'Children''s Art Set', '45,25');
insert into Products (id, product_name, account_id) values (533, 'Spicy Hummus', '29,75');
insert into Products (id, product_name, account_id) values (534, 'Insulated Coffee Mug', '50,99');
insert into Products (id, product_name, account_id) values (535, 'Luxury Rolling Makeup Case', '50,19');
insert into Products (id, product_name, account_id) values (536, 'Beet Salad', '89,65');
insert into Products (id, product_name, account_id) values (537, 'Quinoa and Kale Salad Kit', '77,50');
insert into Products (id, product_name, account_id) values (538, 'Multi-Function Smartphone Holder', '26,65');
insert into Products (id, product_name, account_id) values (539, 'Organic Tomato Ketchup', '20,88');
insert into Products (id, product_name, account_id) values (540, 'Teriyaki Chicken Bowl', '46,77');
insert into Products (id, product_name, account_id) values (541, 'Quinoa Salad', '79,67');
insert into Products (id, product_name, account_id) values (542, 'Coconut Cream Pie Mix', '9,46');
insert into Products (id, product_name, account_id) values (543, 'Dog Collar', '83,17');
insert into Products (id, product_name, account_id) values (544, 'Gardening Gloves with Claws', '44,84');
insert into Products (id, product_name, account_id) values (545, 'Vegan Chickpea Salad', '89,63');
insert into Products (id, product_name, account_id) values (546, 'Honey Mustard Pretzel Bites', '4,83');
insert into Products (id, product_name, account_id) values (547, 'Lemon Basil Pasta Sauce', '44,59');
insert into Products (id, product_name, account_id) values (548, 'Veggie Burger Patties', '22,70');
insert into Products (id, product_name, account_id) values (549, 'Foam Muscle Roller', '43,3');
insert into Products (id, product_name, account_id) values (550, 'Lentil Soup (canned)', '4,65');
insert into Products (id, product_name, account_id) values (551, 'Pet Hair Vacuum Attachment', '27,80');
insert into Products (id, product_name, account_id) values (552, 'Comfortable Bed Pillow', '30,71');
insert into Products (id, product_name, account_id) values (553, 'Marinated Artichokes', '89,45');
insert into Products (id, product_name, account_id) values (554, 'Artisan Bread Loaf', '94,43');
insert into Products (id, product_name, account_id) values (555, 'Smart Plant Monitor', '18,1');
insert into Products (id, product_name, account_id) values (556, 'Microfiber Cleaning Cloths', '60,70');
insert into Products (id, product_name, account_id) values (557, 'Indian Curry Sauce', '55,71');
insert into Products (id, product_name, account_id) values (558, 'Organic Vanilla Bean Ice Cream', '68,71');
insert into Products (id, product_name, account_id) values (559, 'Oatmeal Raisin Cookies', '94,60');
insert into Products (id, product_name, account_id) values (560, 'Oven Mitts with Pocket', '26,61');
insert into Products (id, product_name, account_id) values (561, 'Pet Food Storage Container', '53,45');
insert into Products (id, product_name, account_id) values (562, 'Butternut Squash Soup', '71,49');
insert into Products (id, product_name, account_id) values (563, 'Fitness Jump Rope with LCD Counter', '8,81');
insert into Products (id, product_name, account_id) values (564, 'Chocolate Dipped Fruit', '72,38');
insert into Products (id, product_name, account_id) values (565, 'Inflatable Paddle Board', '18,75');
insert into Products (id, product_name, account_id) values (566, 'Sliced Olives', '30,0');
insert into Products (id, product_name, account_id) values (567, 'Wireless Charging Pad', '88,25');
insert into Products (id, product_name, account_id) values (568, 'Smart WiFi Plug', '81,69');
insert into Products (id, product_name, account_id) values (569, 'Digital Camera', '48,99');
insert into Products (id, product_name, account_id) values (570, 'Honey', '48,2');
insert into Products (id, product_name, account_id) values (571, 'Foam Roller for Muscle Recovery', '84,51');
insert into Products (id, product_name, account_id) values (572, 'Shredded Cheese', '48,30');
insert into Products (id, product_name, account_id) values (573, 'Rice Pilaf Mix', '67,6');
insert into Products (id, product_name, account_id) values (574, 'Herb Garlic Butter', '96,73');
insert into Products (id, product_name, account_id) values (575, 'Baked Potato Chips', '2,68');
insert into Products (id, product_name, account_id) values (576, 'Pumpkin Ice Cream', '92,31');
insert into Products (id, product_name, account_id) values (577, 'Solar Charger', '64,80');
insert into Products (id, product_name, account_id) values (578, 'Oven-Baked Sweet Potato Fries', '8,25');
insert into Products (id, product_name, account_id) values (579, 'Himalayan Salt Grinder', '16,87');
insert into Products (id, product_name, account_id) values (580, 'Summer Tank Dress', '9,88');
insert into Products (id, product_name, account_id) values (581, 'Fitness Jump Box', '97,40');
insert into Products (id, product_name, account_id) values (582, 'Self-Stirring Mug', '2,86');
insert into Products (id, product_name, account_id) values (583, 'Bluetooth Car Adapter', '66,60');
insert into Products (id, product_name, account_id) values (584, 'Beach Cover-Up', '5,98');
insert into Products (id, product_name, account_id) values (585, 'Puffer Winter Coat', '48,60');
insert into Products (id, product_name, account_id) values (586, 'Foot Massager', '73,3');
insert into Products (id, product_name, account_id) values (587, 'Basil Lemonade', '21,57');
insert into Products (id, product_name, account_id) values (588, 'Cacao Nibs', '79,65');
insert into Products (id, product_name, account_id) values (589, 'Sliced Turkey Breast', '86,75');
insert into Products (id, product_name, account_id) values (590, 'Winter Insulated Jacket', '15,54');
insert into Products (id, product_name, account_id) values (591, 'Adjustable Dog Harness', '57,46');
insert into Products (id, product_name, account_id) values (592, 'Chicken Parmesan Dinner Kit', '83,61');
insert into Products (id, product_name, account_id) values (593, 'Dual Function Electric Skillet', '93,85');
insert into Products (id, product_name, account_id) values (594, 'Weighted Blanket', '44,10');
insert into Products (id, product_name, account_id) values (595, 'Smart Thermos', '17,25');
insert into Products (id, product_name, account_id) values (596, 'Organic Honeycrisp Apples', '23,62');
insert into Products (id, product_name, account_id) values (597, 'Coconut Milk', '57,48');
insert into Products (id, product_name, account_id) values (598, 'Glass Water Bottle', '77,53');
insert into Products (id, product_name, account_id) values (599, 'Car Vacuum', '41,35');
insert into Products (id, product_name, account_id) values (600, 'Biodegradable Phone Case', '50,14');
insert into Products (id, product_name, account_id) values (601, 'Outdoor Picnic Blanket', '24,100');
insert into Products (id, product_name, account_id) values (602, 'Gingerbread House Kit', '17,2');
insert into Products (id, product_name, account_id) values (603, 'Slingback Sandals', '84,40');
insert into Products (id, product_name, account_id) values (604, 'LED Canopy Lights', '37,56');
insert into Products (id, product_name, account_id) values (605, 'Wireless Induction Charger', '32,16');
insert into Products (id, product_name, account_id) values (606, 'Bamboo Memory Foam Pillow', '40,44');
insert into Products (id, product_name, account_id) values (607, 'Siphon Coffee Maker', '44,76');
insert into Products (id, product_name, account_id) values (608, 'Nutritional Yeast', '93,18');
insert into Products (id, product_name, account_id) values (609, 'Pet Water Fountain', '95,33');
insert into Products (id, product_name, account_id) values (610, 'LED Strip Light Kit', '35,72');
insert into Products (id, product_name, account_id) values (611, 'Electric Rice Cooker with Steamer', '41,60');
insert into Products (id, product_name, account_id) values (612, 'Egg Noodles', '82,18');
insert into Products (id, product_name, account_id) values (613, 'Mesh Laundry Bags Set', '61,67');
insert into Products (id, product_name, account_id) values (614, 'Kitchen Scale', '26,48');
insert into Products (id, product_name, account_id) values (615, 'Thai Coconut Curry Sauce', '91,96');
insert into Products (id, product_name, account_id) values (616, 'Honey Almond Granola Bars', '37,49');
insert into Products (id, product_name, account_id) values (617, 'Banana Peanut Butter Smoothie', '55,40');
insert into Products (id, product_name, account_id) values (618, 'Set of Herb Garden Markers', '92,41');
insert into Products (id, product_name, account_id) values (619, 'Greek Feta Cheese', '41,1');
insert into Products (id, product_name, account_id) values (620, 'Pumpkin Spice Coffee', '40,32');
insert into Products (id, product_name, account_id) values (621, 'Solar Charger', '18,42');
insert into Products (id, product_name, account_id) values (622, 'Organic Whole Wheat Flour', '59,30');
insert into Products (id, product_name, account_id) values (623, 'Home Office Chair', '75,79');
insert into Products (id, product_name, account_id) values (624, 'Chicken Parmesan Dinner Kit', '5,40');
insert into Products (id, product_name, account_id) values (625, 'Raspberry Lemonade Mix', '34,48');
insert into Products (id, product_name, account_id) values (626, 'Butternut Squash Ravioli', '39,49');
insert into Products (id, product_name, account_id) values (627, 'Denim Jacket', '0,73');
insert into Products (id, product_name, account_id) values (628, 'Portable Air Pump', '38,17');
insert into Products (id, product_name, account_id) values (629, 'Fashionable Fanny Pack', '59,76');
insert into Products (id, product_name, account_id) values (630, 'Digital Alarm Clock', '41,73');
insert into Products (id, product_name, account_id) values (631, 'Active Racerback Tank', '32,85');
insert into Products (id, product_name, account_id) values (632, 'Black Bean Spaghetti', '49,33');
insert into Products (id, product_name, account_id) values (633, 'Chocolate Almond Milk', '62,81');
insert into Products (id, product_name, account_id) values (634, 'Luxury Memory Foam Mattress Topper', '58,21');
insert into Products (id, product_name, account_id) values (635, 'Mixed Nuts', '12,61');
insert into Products (id, product_name, account_id) values (636, 'Tea Set with Infuser', '7,98');
insert into Products (id, product_name, account_id) values (637, 'Lemon Basil Pasta Sauce', '83,20');
insert into Products (id, product_name, account_id) values (638, 'Laptop Sleeve', '76,58');
insert into Products (id, product_name, account_id) values (639, 'Non-Toxic Crayons for Kids', '97,92');
insert into Products (id, product_name, account_id) values (640, 'Olive Oil', '58,95');
insert into Products (id, product_name, account_id) values (641, 'Toilet Paper (12 rolls)', '61,94');
insert into Products (id, product_name, account_id) values (642, 'Smoked Salmon', '98,16');
insert into Products (id, product_name, account_id) values (643, 'Bamboo Bathtub Caddy', '42,28');
insert into Products (id, product_name, account_id) values (644, 'Non-Stick Baking Sheets', '61,97');
insert into Products (id, product_name, account_id) values (645, 'Travel Sewing Kit', '22,68');
insert into Products (id, product_name, account_id) values (646, 'Lemonade Mix', '34,63');
insert into Products (id, product_name, account_id) values (647, 'Heavy Duty Gardening Tool Set', '27,55');
insert into Products (id, product_name, account_id) values (648, 'Tactical Backpack', '8,27');
insert into Products (id, product_name, account_id) values (649, 'Coconut Curry Lentils', '53,86');
insert into Products (id, product_name, account_id) values (650, 'Ginger Turmeric Shots', '60,30');
insert into Products (id, product_name, account_id) values (651, 'Teriyaki Beef Jerky', '76,47');
insert into Products (id, product_name, account_id) values (652, 'Electric Nail File Kit', '48,60');
insert into Products (id, product_name, account_id) values (653, 'Multi-Purpose Scissors', '5,75');
insert into Products (id, product_name, account_id) values (654, 'Classic Cheeseburger Mix', '4,91');
insert into Products (id, product_name, account_id) values (655, 'Elegant Maxi Skirt', '16,44');
insert into Products (id, product_name, account_id) values (656, 'Frozen Cauliflower Rice', '51,46');
insert into Products (id, product_name, account_id) values (657, 'Tomato Sauce', '76,27');
insert into Products (id, product_name, account_id) values (658, 'Eco-Friendly Cleaning Cloths', '12,85');
insert into Products (id, product_name, account_id) values (659, 'Car Sunshade', '15,15');
insert into Products (id, product_name, account_id) values (660, 'Veggie Burger Patties', '47,27');
insert into Products (id, product_name, account_id) values (661, 'Home Brewing Starter Kit', '23,69');
insert into Products (id, product_name, account_id) values (662, 'Cat Tree with Scratching Posts', '3,53');
insert into Products (id, product_name, account_id) values (663, 'Magnetic Phone Car Mount', '98,20');
insert into Products (id, product_name, account_id) values (664, 'Shower Curtain Hooks', '7,31');
insert into Products (id, product_name, account_id) values (665, 'Wireless Music Receiver', '65,26');
insert into Products (id, product_name, account_id) values (666, 'Pressure Cooker', '22,3');
insert into Products (id, product_name, account_id) values (667, 'Breezy Off-The-Shoulder Top', '37,76');
insert into Products (id, product_name, account_id) values (668, 'Smoked Gouda Cheese', '71,91');
insert into Products (id, product_name, account_id) values (669, 'Pet Safety Belt for Car', '89,64');
insert into Products (id, product_name, account_id) values (670, 'Almond Joy Protein Bars', '27,76');
insert into Products (id, product_name, account_id) values (671, 'Vegan chocolate chip cookies', '9,19');
insert into Products (id, product_name, account_id) values (672, 'Travel Mug with Leak-Proof Lid', '8,96');
insert into Products (id, product_name, account_id) values (673, 'Pork Tenderloin', '83,52');
insert into Products (id, product_name, account_id) values (674, 'Puzzle Mat', '31,98');
insert into Products (id, product_name, account_id) values (675, 'Butternut Squash Ravioli', '68,93');
insert into Products (id, product_name, account_id) values (676, 'Rechargeable Battery Organizer', '64,21');
insert into Products (id, product_name, account_id) values (677, 'Zucchini Noodles', '32,42');
insert into Products (id, product_name, account_id) values (678, 'High-Speed Hand Blender', '87,48');
insert into Products (id, product_name, account_id) values (679, 'Electric Kettle with Temperature Control', '11,45');
insert into Products (id, product_name, account_id) values (680, 'Safety Goggles', '1,9');
insert into Products (id, product_name, account_id) values (681, 'Adjustable Yoga Mat Strap', '48,94');
insert into Products (id, product_name, account_id) values (682, 'Spinach and Feta Wraps', '7,28');
insert into Products (id, product_name, account_id) values (683, 'Vegan Taco Seasoning', '25,49');
insert into Products (id, product_name, account_id) values (684, 'Classic White T-Shirt', '8,96');
insert into Products (id, product_name, account_id) values (685, 'Portable Hammock with Stand', '82,100');
insert into Products (id, product_name, account_id) values (686, 'USB-C Hub', '18,8');
insert into Products (id, product_name, account_id) values (687, 'Vegan Caesar Dressing', '49,6');
insert into Products (id, product_name, account_id) values (688, 'Pet Safety Belt for Car', '25,51');
insert into Products (id, product_name, account_id) values (689, 'Smartphone Photography Ring Light', '9,69');
insert into Products (id, product_name, account_id) values (690, 'Camping Tent', '90,48');
insert into Products (id, product_name, account_id) values (691, 'Peas (frozen)', '94,47');
insert into Products (id, product_name, account_id) values (692, 'Winter Knit Beanie', '49,78');
insert into Products (id, product_name, account_id) values (693, 'Fruit Medley Juice', '82,89');
insert into Products (id, product_name, account_id) values (694, 'Protein Powder', '40,7');
insert into Products (id, product_name, account_id) values (695, 'Peanut Butter Filled Pretzels', '78,16');
insert into Products (id, product_name, account_id) values (696, 'Leek and Potato Soup', '3,50');
insert into Products (id, product_name, account_id) values (697, 'Cocoa Powder', '50,37');
insert into Products (id, product_name, account_id) values (698, 'Dishwasher Safe Cutting Board', '46,18');
insert into Products (id, product_name, account_id) values (699, 'Cinnamon Roll Dough', '68,79');
insert into Products (id, product_name, account_id) values (700, 'Roasted Garlic Aioli', '58,69');
insert into Products (id, product_name, account_id) values (701, 'Pocket Blanket', '27,17');
insert into Products (id, product_name, account_id) values (702, 'Portable Phone Mug Holder', '89,73');
insert into Products (id, product_name, account_id) values (703, 'Carrot Ginger Soup', '74,18');
insert into Products (id, product_name, account_id) values (704, 'Smartphone Projector Kit', '58,95');
insert into Products (id, product_name, account_id) values (705, 'Floral Wrap Top', '34,47');
insert into Products (id, product_name, account_id) values (706, 'Vegan Tacos', '9,38');
insert into Products (id, product_name, account_id) values (707, 'Noise Cancelling Ear Muffs', '30,0');
insert into Products (id, product_name, account_id) values (708, 'Leather Notebook Cover', '22,65');
insert into Products (id, product_name, account_id) values (709, 'Coconut Chia Pudding', '92,10');
insert into Products (id, product_name, account_id) values (710, 'Roasted Chickpeas', '36,16');
insert into Products (id, product_name, account_id) values (711, 'Chocolate Dipped Fruit', '12,42');
insert into Products (id, product_name, account_id) values (712, 'Vanilla Bean Greek Yogurt', '72,79');
insert into Products (id, product_name, account_id) values (713, 'Weighted Blanket for Adults', '55,51');
insert into Products (id, product_name, account_id) values (714, 'Fitness Foam Roller', '77,2');
insert into Products (id, product_name, account_id) values (715, 'Chia Seed Pudding', '3,9');
insert into Products (id, product_name, account_id) values (716, 'Digital Kitchen Timer', '37,99');
insert into Products (id, product_name, account_id) values (717, 'Sweet Chili Thai Sauce', '64,95');
insert into Products (id, product_name, account_id) values (718, 'Safety First Aid Kit', '64,96');
insert into Products (id, product_name, account_id) values (719, 'Electric Food Steamer', '5,96');
insert into Products (id, product_name, account_id) values (720, 'Handheld Vacuum', '12,80');
insert into Products (id, product_name, account_id) values (721, 'Caramel Sauce', '93,13');
insert into Products (id, product_name, account_id) values (722, 'Reflective Safety Vest', '7,68');
insert into Products (id, product_name, account_id) values (723, 'Savory Trail Mix', '82,55');
insert into Products (id, product_name, account_id) values (724, 'Infrared Space Heater', '0,91');
insert into Products (id, product_name, account_id) values (725, 'Customizable Name Plate', '68,14');
insert into Products (id, product_name, account_id) values (726, 'Cushion Covers', '6,99');
insert into Products (id, product_name, account_id) values (727, 'Noise Reduction Headphones', '59,100');
insert into Products (id, product_name, account_id) values (728, 'Mechanical Pencil Set', '35,22');
insert into Products (id, product_name, account_id) values (729, 'Garlic Parmesan Roasted Potatoes', '10,67');
insert into Products (id, product_name, account_id) values (730, 'Veggie Chips Variety Pack', '53,94');
insert into Products (id, product_name, account_id) values (731, 'Oven Mitts with Pocket', '28,74');
insert into Products (id, product_name, account_id) values (732, 'Chicken Fajita Kit', '57,99');
insert into Products (id, product_name, account_id) values (733, 'Coconut Cashew Yogurt', '0,64');
insert into Products (id, product_name, account_id) values (734, 'Hiking Gaiters', '17,19');
insert into Products (id, product_name, account_id) values (735, 'Smart Fitness Scale', '20,65');
insert into Products (id, product_name, account_id) values (736, 'Reusable Snack Bags', '1,13');
insert into Products (id, product_name, account_id) values (737, 'Himalayan Pink Salt', '97,17');
insert into Products (id, product_name, account_id) values (738, 'Italian Sausage Links', '22,30');
insert into Products (id, product_name, account_id) values (739, 'Classic Cheeseburger Mix', '51,77');
insert into Products (id, product_name, account_id) values (740, 'Buffalo Sauce', '0,43');
insert into Products (id, product_name, account_id) values (741, 'Cinnamon Apple Sauce', '93,77');
insert into Products (id, product_name, account_id) values (742, 'Basmati Rice', '6,6');
insert into Products (id, product_name, account_id) values (743, 'Over-the-Door Shoe Organizer', '10,67');
insert into Products (id, product_name, account_id) values (744, 'Streaming Device', '15,35');
insert into Products (id, product_name, account_id) values (745, 'Portable USB-C Monitor', '18,11');
insert into Products (id, product_name, account_id) values (746, 'Sesame Oil', '80,3');
insert into Products (id, product_name, account_id) values (747, 'Spinach and Ricotta Ravioli', '26,43');
insert into Products (id, product_name, account_id) values (748, 'Pet Leash', '48,16');
insert into Products (id, product_name, account_id) values (749, 'Chocolate Covered Pretzels', '21,64');
insert into Products (id, product_name, account_id) values (750, 'Spicy Tuna Sushi Kit', '42,16');
insert into Products (id, product_name, account_id) values (751, 'Silicone Cooking Utensils Set', '11,100');
insert into Products (id, product_name, account_id) values (752, 'Smart Light Bulbs', '62,34');
insert into Products (id, product_name, account_id) values (753, 'Travel Organizer', '18,92');
insert into Products (id, product_name, account_id) values (754, 'Silicone Baking Mats', '25,34');
insert into Products (id, product_name, account_id) values (755, 'Fresh Basil', '10,0');
insert into Products (id, product_name, account_id) values (756, 'Fruit Infuser Water Bottle', '3,31');
insert into Products (id, product_name, account_id) values (757, 'Pumpkin Puree', '58,19');
insert into Products (id, product_name, account_id) values (758, 'Stainless Steel Water Pitcher', '22,82');
insert into Products (id, product_name, account_id) values (759, 'Cabbage', '91,40');
insert into Products (id, product_name, account_id) values (760, 'Lockable Bicycle Chain', '87,43');
insert into Products (id, product_name, account_id) values (761, 'Antique Style Clock', '99,52');
insert into Products (id, product_name, account_id) values (762, 'Zesty Garlic Marinade', '58,65');
insert into Products (id, product_name, account_id) values (763, 'Green Smoothie Mix', '100,35');
insert into Products (id, product_name, account_id) values (764, 'Canned Coconut Milk', '96,49');
insert into Products (id, product_name, account_id) values (765, 'Solar String Lights', '13,43');
insert into Products (id, product_name, account_id) values (766, 'Vanilla Bean Greek Yogurt', '53,6');
insert into Products (id, product_name, account_id) values (767, 'Portable Charcoal Grill', '16,25');
insert into Products (id, product_name, account_id) values (768, 'Honey mustard chicken tenders', '63,21');
insert into Products (id, product_name, account_id) values (769, 'Oatmeal Raisin Cookies', '85,3');
insert into Products (id, product_name, account_id) values (770, 'Caraway Rye Bread', '42,8');
insert into Products (id, product_name, account_id) values (771, 'Crispy Rice Treats', '68,99');
insert into Products (id, product_name, account_id) values (772, 'Garlic Herb Seasoning', '53,48');
insert into Products (id, product_name, account_id) values (773, 'Chicken Broth', '53,40');
insert into Products (id, product_name, account_id) values (774, 'Savory Oatmeal', '79,81');
insert into Products (id, product_name, account_id) values (775, 'Electronic Drum Kit', '15,37');
insert into Products (id, product_name, account_id) values (776, 'LED Flashing Pet Collar', '17,18');
insert into Products (id, product_name, account_id) values (777, 'Thai Basil Fried Rice', '13,65');
insert into Products (id, product_name, account_id) values (778, 'Relaxed Fit Henley Shirt', '67,29');
insert into Products (id, product_name, account_id) values (779, 'Streaming Device', '100,38');
insert into Products (id, product_name, account_id) values (780, 'Lasagna Noodles', '47,54');
insert into Products (id, product_name, account_id) values (781, 'Professional Chef Knife', '4,85');
insert into Products (id, product_name, account_id) values (782, 'Chiffon Blouse', '38,4');
insert into Products (id, product_name, account_id) values (783, 'Honey Sesame Chicken', '42,96');
insert into Products (id, product_name, account_id) values (784, 'Coconut Yogurt', '51,46');
insert into Products (id, product_name, account_id) values (785, 'Wall Calendar', '85,24');
insert into Products (id, product_name, account_id) values (786, 'Compact Electric Kettle', '43,65');
insert into Products (id, product_name, account_id) values (787, 'Reusable Food Storage Bags', '35,91');
insert into Products (id, product_name, account_id) values (788, 'Roasted Chickpeas', '73,57');
insert into Products (id, product_name, account_id) values (789, 'Cinnamon Sugar Mix', '3,43');
insert into Products (id, product_name, account_id) values (790, 'Paint By Numbers Kit', '60,51');
insert into Products (id, product_name, account_id) values (791, 'Popcorn Chicken', '54,17');
insert into Products (id, product_name, account_id) values (792, 'Almond Crunch Granola Bars', '30,79');
insert into Products (id, product_name, account_id) values (793, 'Utility Cargo Pants', '72,46');
insert into Products (id, product_name, account_id) values (794, 'Portable Ice Maker', '72,95');
insert into Products (id, product_name, account_id) values (795, 'Smartphone Projector', '24,43');
insert into Products (id, product_name, account_id) values (796, 'Brazil Nuts', '4,41');
insert into Products (id, product_name, account_id) values (797, 'Outdoor Portable Fire Pit', '84,92');
insert into Products (id, product_name, account_id) values (798, 'Almond Quinoa Salad', '77,80');
insert into Products (id, product_name, account_id) values (799, 'Mini Hand Gesture Drone', '82,69');
insert into Products (id, product_name, account_id) values (800, 'Kitchen Scale', '38,52');
insert into Products (id, product_name, account_id) values (801, 'Car Vacuum', '14,20');
insert into Products (id, product_name, account_id) values (802, 'Athletic Compression Tights', '100,62');
insert into Products (id, product_name, account_id) values (803, 'Garden Vegetable Soup', '45,37');
insert into Products (id, product_name, account_id) values (804, 'Handheld Garment Steamer', '2,85');
insert into Products (id, product_name, account_id) values (805, 'Smart Water Bottle', '78,75');
insert into Products (id, product_name, account_id) values (806, 'Smart Thermostat', '32,80');
insert into Products (id, product_name, account_id) values (807, 'Bluetooth Tracker', '34,62');
insert into Products (id, product_name, account_id) values (808, 'Chic Jumpsuit', '51,30');
insert into Products (id, product_name, account_id) values (809, 'Buffalo Cauliflower Wings', '87,68');
insert into Products (id, product_name, account_id) values (810, 'Set of Silicone Cooking Utensils', '38,85');
insert into Products (id, product_name, account_id) values (811, 'Vegetable Samosas', '79,26');
insert into Products (id, product_name, account_id) values (812, 'Apricot Jam', '24,27');
insert into Products (id, product_name, account_id) values (813, 'USB Desk Fan', '34,39');
insert into Products (id, product_name, account_id) values (814, 'Cheesy Broccoli Soup Mix', '54,90');
insert into Products (id, product_name, account_id) values (815, 'Savory Rice Cakes', '94,14');
insert into Products (id, product_name, account_id) values (816, 'Basketball', '66,18');
insert into Products (id, product_name, account_id) values (817, 'Digital Bullet Journal', '11,100');
insert into Products (id, product_name, account_id) values (818, 'Sun Protection Clothing', '9,92');
insert into Products (id, product_name, account_id) values (819, 'Laundry Detergent', '69,55');
insert into Products (id, product_name, account_id) values (820, 'Collapsible Colander', '29,67');
insert into Products (id, product_name, account_id) values (821, 'Wooden Blocks', '10,64');
insert into Products (id, product_name, account_id) values (822, 'Automatic Pet Feeder', '71,52');
insert into Products (id, product_name, account_id) values (823, 'Compact Dishwasher', '20,15');
insert into Products (id, product_name, account_id) values (824, 'Pasta Sauce Mix', '50,15');
insert into Products (id, product_name, account_id) values (825, 'Wall Planner', '9,80');
insert into Products (id, product_name, account_id) values (826, 'Rice Noodles', '86,39');
insert into Products (id, product_name, account_id) values (827, 'Dog Training Collar', '35,40');
insert into Products (id, product_name, account_id) values (828, 'Fresh Strawberries', '30,74');
insert into Products (id, product_name, account_id) values (829, 'Portable Camping Shower', '62,97');
insert into Products (id, product_name, account_id) values (830, 'Travel Document Organizer', '22,57');
insert into Products (id, product_name, account_id) values (831, 'Organic Black Bean Burger', '31,23');
insert into Products (id, product_name, account_id) values (832, 'Low-Fat Cottage Cheese', '55,20');
insert into Products (id, product_name, account_id) values (833, 'Frozen Broccoli', '11,28');
insert into Products (id, product_name, account_id) values (834, 'Sweet Cherry Tomatoes', '59,87');
insert into Products (id, product_name, account_id) values (835, 'Cheese Stuffed Jalapenos', '85,29');
insert into Products (id, product_name, account_id) values (836, 'Beach Cover-Up', '94,12');
insert into Products (id, product_name, account_id) values (837, 'Taro Chips', '14,23');
insert into Products (id, product_name, account_id) values (838, 'Noise Cancelling Ear Muffs', '5,45');
insert into Products (id, product_name, account_id) values (839, 'Cabbage', '84,42');
insert into Products (id, product_name, account_id) values (840, 'Smashed Avocado with Lime', '9,57');
insert into Products (id, product_name, account_id) values (841, 'Herbal Tea Sampler Box', '34,17');
insert into Products (id, product_name, account_id) values (842, 'Water Bottle', '29,52');
insert into Products (id, product_name, account_id) values (843, 'Honey Almond Granola Bars', '20,30');
insert into Products (id, product_name, account_id) values (844, 'Garden Hose', '92,58');
insert into Products (id, product_name, account_id) values (845, 'Popcorn Chicken', '71,9');
insert into Products (id, product_name, account_id) values (846, 'Apple Juice', '38,25');
insert into Products (id, product_name, account_id) values (847, 'Children''s Gardening Set', '7,3');
insert into Products (id, product_name, account_id) values (848, 'Puzzle 3D Model Kit', '70,34');
insert into Products (id, product_name, account_id) values (849, 'Ginger Turmeric Shots', '8,37');
insert into Products (id, product_name, account_id) values (850, 'Lightweight Workout Tank', '47,32');
insert into Products (id, product_name, account_id) values (851, 'Ready-to-Eat Chili', '21,24');
insert into Products (id, product_name, account_id) values (852, 'Vegetable Curry', '36,15');
insert into Products (id, product_name, account_id) values (853, 'Cucumber Relish', '82,70');
insert into Products (id, product_name, account_id) values (854, 'Almond Joy Snack Bars', '63,56');
insert into Products (id, product_name, account_id) values (855, 'Savory Quinoa Pudding', '44,13');
insert into Products (id, product_name, account_id) values (856, 'Silicone Baking Mats', '88,41');
insert into Products (id, product_name, account_id) values (857, 'Kids'' Learning Tablet', '18,92');
insert into Products (id, product_name, account_id) values (858, 'Plant Pot Drip Trays', '46,61');
insert into Products (id, product_name, account_id) values (859, 'Training Soccer Ball', '11,55');
insert into Products (id, product_name, account_id) values (860, 'Wrap Jumpsuit', '40,41');
insert into Products (id, product_name, account_id) values (861, 'Vintage Button-Down Shirt', '61,21');
insert into Products (id, product_name, account_id) values (862, 'Reversible Swimming Pool Lounger', '84,58');
insert into Products (id, product_name, account_id) values (863, 'Zesty Cilantro Lime Dressing', '46,58');
insert into Products (id, product_name, account_id) values (864, 'Whole Wheat Pasta', '7,82');
insert into Products (id, product_name, account_id) values (865, 'Pumpkin Puree', '95,99');
insert into Products (id, product_name, account_id) values (866, 'Matcha Green Tea Powder', '64,55');
insert into Products (id, product_name, account_id) values (867, 'Pretzel Bites', '77,72');
insert into Products (id, product_name, account_id) values (868, 'Stylish Combat Boots', '54,64');
insert into Products (id, product_name, account_id) values (869, 'Sliced Strawberries', '16,73');
insert into Products (id, product_name, account_id) values (870, 'Organic Black Bean Burger', '100,23');
insert into Products (id, product_name, account_id) values (871, 'Mini Food Processor', '56,91');
insert into Products (id, product_name, account_id) values (872, 'Cabbage Slaw Mix', '1,96');
insert into Products (id, product_name, account_id) values (873, 'Elderberry Syrup Kit', '75,44');
insert into Products (id, product_name, account_id) values (874, 'Spinach and Cheese Stuffed Shells', '22,19');
insert into Products (id, product_name, account_id) values (875, 'Ceramic Knife Set', '79,31');
insert into Products (id, product_name, account_id) values (876, 'Leather Wallet', '29,81');
insert into Products (id, product_name, account_id) values (877, 'Classic Baseball Cap', '20,99');
insert into Products (id, product_name, account_id) values (878, 'Coffee Maker', '30,76');
insert into Products (id, product_name, account_id) values (879, 'Chipotle Black Bean Burger', '14,61');
insert into Products (id, product_name, account_id) values (880, 'Kale Salad with Lemon Dressing', '14,66');
insert into Products (id, product_name, account_id) values (881, 'Wrap Jumpsuit', '15,72');
insert into Products (id, product_name, account_id) values (882, 'Motorcycle Phone Mount', '20,8');
insert into Products (id, product_name, account_id) values (883, 'Freestanding Wine Rack', '16,47');
insert into Products (id, product_name, account_id) values (884, 'Adjustable Laptop Stand', '8,95');
insert into Products (id, product_name, account_id) values (885, 'Chino Shorts', '47,56');
insert into Products (id, product_name, account_id) values (886, 'Quality Chef Apron', '44,57');
insert into Products (id, product_name, account_id) values (887, 'Compact Digital Camera', '34,27');
insert into Products (id, product_name, account_id) values (888, 'Frozen Salmon Filets', '48,37');
insert into Products (id, product_name, account_id) values (889, 'Magnetic Phone Car Mount', '15,59');
insert into Products (id, product_name, account_id) values (890, 'Wireless Keyboard and Mouse Combo', '7,75');
insert into Products (id, product_name, account_id) values (891, 'Frozen Broccoli', '83,93');
insert into Products (id, product_name, account_id) values (892, 'Frozen Fruit Medley', '61,60');
insert into Products (id, product_name, account_id) values (893, 'Whole Grain Cereal', '43,28');
insert into Products (id, product_name, account_id) values (894, 'Mango Chutney', '76,45');
insert into Products (id, product_name, account_id) values (895, 'Desk Lamp with USB Port', '69,33');
insert into Products (id, product_name, account_id) values (896, 'Buffalo Cauliflower Bites', '15,14');
insert into Products (id, product_name, account_id) values (897, 'Sweet Potatoes', '53,40');
insert into Products (id, product_name, account_id) values (898, 'Spicy Beef Taco Mix', '6,41');
insert into Products (id, product_name, account_id) values (899, 'Toy Building Set', '67,2');
insert into Products (id, product_name, account_id) values (900, 'Fresh Basil Pesto', '71,47');
insert into Products (id, product_name, account_id) values (901, 'Decorative Throw Blanket', '82,9');
insert into Products (id, product_name, account_id) values (902, 'Cinnamon Sugar Popcorn', '29,25');
insert into Products (id, product_name, account_id) values (903, 'Adjustable Stand for Tablets and Smartphones', '16,73');
insert into Products (id, product_name, account_id) values (904, 'Wooden Kitchen Utensil Set', '62,25');
insert into Products (id, product_name, account_id) values (905, 'Fitness Foam Roller', '63,22');
insert into Products (id, product_name, account_id) values (906, 'Almond Flour', '48,47');
insert into Products (id, product_name, account_id) values (907, 'Reversible Comforter Set', '93,43');
insert into Products (id, product_name, account_id) values (908, 'Pet Activity Tracker', '29,25');
insert into Products (id, product_name, account_id) values (909, 'Frozen Cauliflower Rice', '2,59');
insert into Products (id, product_name, account_id) values (910, 'Children''s Educational Workbook', '85,53');
insert into Products (id, product_name, account_id) values (911, 'Garam Masala Spice Blend', '3,34');
insert into Products (id, product_name, account_id) values (912, 'Kale and Quinoa Salad', '30,48');
insert into Products (id, product_name, account_id) values (913, 'Ready-to-Eat Chili', '39,50');
insert into Products (id, product_name, account_id) values (914, 'Ramen Noodle Soup Cups', '73,25');
insert into Products (id, product_name, account_id) values (915, 'Pressure Cooker', '51,17');
insert into Products (id, product_name, account_id) values (916, 'Wireless Wi-Fi Extender', '58,29');
insert into Products (id, product_name, account_id) values (917, 'Basil Lemonade', '70,53');
insert into Products (id, product_name, account_id) values (918, 'Whole Wheat Pasta', '71,70');
insert into Products (id, product_name, account_id) values (919, 'Personal Blender with Travel Lid', '34,33');
insert into Products (id, product_name, account_id) values (920, 'Almond Flour Pancake Mix', '35,32');
insert into Products (id, product_name, account_id) values (921, 'Frozen Mixed Vegetables', '74,68');
insert into Products (id, product_name, account_id) values (922, 'Reusable Silicone Food Storage Bags', '69,27');
insert into Products (id, product_name, account_id) values (923, 'Personal Blender with Cups', '97,46');
insert into Products (id, product_name, account_id) values (924, 'Wooden Kitchen Utensil Set', '80,73');
insert into Products (id, product_name, account_id) values (925, 'Crispy Tofu Bites', '73,75');
insert into Products (id, product_name, account_id) values (926, 'Personalized Pet ID Tags', '34,95');
insert into Products (id, product_name, account_id) values (927, 'Chocolate Chip Cookie Mix', '4,37');
insert into Products (id, product_name, account_id) values (928, 'Canvas High-Top Sneakers', '78,82');
insert into Products (id, product_name, account_id) values (929, 'Garlic Breadsticks', '97,5');
insert into Products (id, product_name, account_id) values (930, 'Customizable Wall Calendar', '33,20');
insert into Products (id, product_name, account_id) values (931, 'Pet Grooming Gloves', '84,7');
insert into Products (id, product_name, account_id) values (932, 'Organic Baby Carrots', '69,95');
insert into Products (id, product_name, account_id) values (933, 'Two-Tone Windbreaker', '95,80');
insert into Products (id, product_name, account_id) values (934, 'Folding Table', '12,54');
insert into Products (id, product_name, account_id) values (935, 'Toilet Paper (12 rolls)', '65,76');
insert into Products (id, product_name, account_id) values (936, 'Fishing Tackle Box', '91,2');
insert into Products (id, product_name, account_id) values (937, 'Roasted Vegetable Medley', '33,58');
insert into Products (id, product_name, account_id) values (938, 'Elderberry Syrup Kit', '93,20');
insert into Products (id, product_name, account_id) values (939, 'Garden Kneeler and Seat', '93,27');
insert into Products (id, product_name, account_id) values (940, 'Organic Lentil Soup', '16,77');
insert into Products (id, product_name, account_id) values (941, 'Carrot and Celery Sticks', '38,83');
insert into Products (id, product_name, account_id) values (942, 'Foot Massager', '84,37');
insert into Products (id, product_name, account_id) values (943, 'Chocolate Chip Energy Balls', '77,97');
insert into Products (id, product_name, account_id) values (944, 'Classic Cheeseburger Mix', '15,32');
insert into Products (id, product_name, account_id) values (945, 'Children''s Garden Tool Set', '55,91');
insert into Products (id, product_name, account_id) values (946, 'Sweet Potato Chips', '29,72');
insert into Products (id, product_name, account_id) values (947, 'DIY Candle Making Kit', '33,11');
insert into Products (id, product_name, account_id) values (948, 'Raisin Cinnamon Granola', '12,70');
insert into Products (id, product_name, account_id) values (949, 'Outdoor Mosquito Repellent Lantern', '58,95');
insert into Products (id, product_name, account_id) values (950, 'Water-Resistant Bluetooth Speaker', '55,45');
insert into Products (id, product_name, account_id) values (951, 'Emergency Preparedness Kit', '28,24');
insert into Products (id, product_name, account_id) values (952, 'Balsamic Glaze', '18,32');
insert into Products (id, product_name, account_id) values (953, 'Sliced Turkey Breast', '35,58');
insert into Products (id, product_name, account_id) values (954, 'Smart Wi-Fi Light Bulbs', '59,92');
insert into Products (id, product_name, account_id) values (955, 'Vegan Protein Powder', '65,80');
insert into Products (id, product_name, account_id) values (956, 'Chicken Breasts', '33,79');
insert into Products (id, product_name, account_id) values (957, 'Cheesy Cauliflower Bake', '88,10');
insert into Products (id, product_name, account_id) values (958, 'Wooden Puzzle Game', '93,5');
insert into Products (id, product_name, account_id) values (959, 'Lentil Vegetable Curry', '43,68');
insert into Products (id, product_name, account_id) values (960, 'Non-Stick Crepe Pan', '87,82');
insert into Products (id, product_name, account_id) values (961, 'Spicy Hummus', '77,48');
insert into Products (id, product_name, account_id) values (962, 'Hydration Backpack', '9,94');
insert into Products (id, product_name, account_id) values (963, 'Sliced Cucumbers', '40,29');
insert into Products (id, product_name, account_id) values (964, 'Foldable Yoga Mat Carry Bag', '41,71');
insert into Products (id, product_name, account_id) values (965, 'Baby Monitor', '89,4');
insert into Products (id, product_name, account_id) values (966, 'Grass Fed Beef Patties', '86,82');
insert into Products (id, product_name, account_id) values (967, 'Chia Seeds', '76,51');
insert into Products (id, product_name, account_id) values (968, 'Frozen Fruit Medley', '49,60');
insert into Products (id, product_name, account_id) values (969, 'Chocolate Coconut Granola', '78,74');
insert into Products (id, product_name, account_id) values (970, 'Cotton Pajama Set', '52,74');
insert into Products (id, product_name, account_id) values (971, 'LED Strip Light Kit', '80,32');
insert into Products (id, product_name, account_id) values (972, 'Cinnamon Roll Kit', '93,53');
insert into Products (id, product_name, account_id) values (973, 'Adjustable Window Blind', '46,54');
insert into Products (id, product_name, account_id) values (974, 'Baked Falafel Balls', '13,15');
insert into Products (id, product_name, account_id) values (975, 'Baked Falafel Balls', '70,69');
insert into Products (id, product_name, account_id) values (976, 'Collapsible Storage Crates', '35,45');
insert into Products (id, product_name, account_id) values (977, 'Almond Flour Cookies', '57,83');
insert into Products (id, product_name, account_id) values (978, 'Pineapple Coconut Rice Mix', '94,85');
insert into Products (id, product_name, account_id) values (979, 'Organic Black Beans', '86,25');
insert into Products (id, product_name, account_id) values (980, 'Almond Butter', '51,18');
insert into Products (id, product_name, account_id) values (981, 'Greek Yogurt Parfait', '3,42');
insert into Products (id, product_name, account_id) values (982, 'Heated Throw Blanket', '94,43');
insert into Products (id, product_name, account_id) values (983, 'Set of Silicone Cooking Utensils', '96,16');
insert into Products (id, product_name, account_id) values (984, 'Patterned Knit Scarf', '38,85');
insert into Products (id, product_name, account_id) values (985, 'Portable USB-C Monitor', '64,89');
insert into Products (id, product_name, account_id) values (986, 'LED Strip Lights', '77,38');
insert into Products (id, product_name, account_id) values (987, 'Memory Card', '30,39');
insert into Products (id, product_name, account_id) values (988, 'Vegetable Lentil Soup', '1,75');
insert into Products (id, product_name, account_id) values (989, 'Pine Nuts', '11,66');
insert into Products (id, product_name, account_id) values (990, 'Spicy Snack Mix', '46,28');
insert into Products (id, product_name, account_id) values (991, 'Board Game', '15,15');
insert into Products (id, product_name, account_id) values (992, 'Eggs (dozen)', '57,68');
insert into Products (id, product_name, account_id) values (993, 'Field Journal', '82,15');
insert into Products (id, product_name, account_id) values (994, 'Wireless Wi-Fi Extender', '66,85');
insert into Products (id, product_name, account_id) values (995, 'Oatmeal Raisin Cookies', '77,77');
insert into Products (id, product_name, account_id) values (996, 'Electric Heat Press Machine', '26,42');
insert into Products (id, product_name, account_id) values (997, 'Adjustable Standing Desk', '14,15');
insert into Products (id, product_name, account_id) values (998, 'Mini Indoor Hydroponic Garden', '74,53');
insert into Products (id, product_name, account_id) values (999, 'Balsamic Glaze', '89,72');
insert into Products (id, product_name, account_id) values (1000, 'Pet Camera with Treat Dispenser', '11,67');
